### ISSUE TITLE
WMF 5 and Get-DscConfiguration gives a schema error

### ISSUE THREAD

**Issue by FrodeOA** [PowerShell/xAdcsDeployment#14]
Hello, I've been using this resource on a wmf 5 test box and it gives me the following error after running Get-DscConfiguration:

Job {3884F744-0552-11E6-80C2-001DD8B73C08} : 
MIResult: 13
Error Message: The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The IsCA key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file.
Message ID: GetOperationResultInvalidResultFormat
Error Category: 8
Error Code: 13
Error Type: MI

Test-DscConfiguration returns true

**Comment by PlagueHO** [comment]
@FrodeOA - Good catch there and thanks for reporting it. I'm in the process of reworking this DSC resource module and adding Unit and Integration tests (which would have caught this issue). I'll get a PR put through to resolve this.

**Comment by PlagueHO** [comment]
@FrodeOA - sorry I haven't got to this one yet - it's on my Todo list.

**Comment by theJasonHelmick** [comment]
Is there any word on this issue yet? It's blocking.

**Comment by PlagueHO** [comment]
@theJasonHelmick  - Doh. Apologies. This one slipped. I'll take a look this weekend.

**Comment by theJasonHelmick** [comment]
Thank you! -- its much appreciated -- have been fixing by adding IsCA to schema -- but not sure if thats what you want --- have a coworker that can fork and send pull request if desired.  Thanks again!

**Comment by PlagueHO** [comment]
@theJasonHelmick - no worries!

I'm thinking, to bring it inline with other DSC resources (e.g. [xSerivce](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1#L203)) we should actually probably remove IsCA property and set "Ensure" to be "Present" if the CA is installed an "Absent" if the CA is not installed when Get-TargetResource is called.

Would this be OK with you?

I'll also try and add some integration tests to this resource at the same time so that we don't regress.

I'll do a little bit of clean up to the resource as well so that my commit will be accepted (the resource currently violates a few guidelines). Won't take me long, I'll have it done today.

**Comment by theJasonHelmick** [comment]
Sounds great! — in fact my coworker had discussed that route — Thank you so much!  WE have an open source project that is doing some pretty extensive DSC ADCS configs and this is very helpful to use on the Get return!

Cheers!

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com <http://www.pluralsight.com/>

**Comment by PlagueHO** [comment]
@theJasonHelmick - Awesome! I'm on it now :smile:

**Comment by PlagueHO** [comment]
Hi @theJasonHelmick  - I have submitted a PR for this. See #19.

Not sure how long it will take to get this merged (the DSC team are pretty busy at the moment). Feel free to use the code in my fork if you want to try it out before then.

**Comment by majst32** [comment]
Awesome, thanks so much for fixing - we will start using it!!

**Comment by PlagueHO** [comment]
@majst32 - no problem! Let me know if you run into any issues. Cheers!
