### ISSUE TITLE
Convert xADCSWebEnrollment to use IsSingleInstance resource design pattern

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xAdcsDeployment#7]
The xADCSWebEnrollment resource currently requires a Name key field that gives the impression that more than one instance could be installed.

I think it should be updated to use the IsSingleInstance design pattern as defined in [this post](
http://blogs.msdn.com/b/powershell/archive/2015/06/23/want-to-write-a-dsc-resource-where-only-a-single-instance-can-be-configured.aspx).

**Comment by PlagueHO** [comment]
@TravisEz13 - I'm putting some work into these resource at the moment. Is it worth implementing this change? It would be a breaking change, but I think it needs to happen.

**Comment by TravisEz13** [comment]
@PlagueHO I think it should happen.  You are aware this is a best practice because DSC doesn't currently support a true singleton (a class without a key.)   So perhaps, this support would be added in the future.  I still think this should be done as:

1. it fixes the current schema issues
2. it identifies the resources with this pattern.

**Comment by PlagueHO** [comment]
Cool. I'll get this one done over the next week.
